---
title: "Bayesian Linear Regression-Capstone Project"
author: "Summer Dahlen"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: STA 6257 - Advanced Statistical Modeling
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

## Week 2

### A tutorial on Bayesian Normal linear regression

This article provides a breakdown of how a Bayesian Linear Regression
works, detailing how one needs to take the priori knowledge/distribution
(which is previous knowledge) to get the posterior
knowledge/distribution (which is the priori knowledge with unknowns in
the data). This article gives an example of the priori and posteriori
knowledge by using the example of sonic nozzle calibration in metrology
and showing a graph of a posterior regression with a posterior
prediction. A sensitivity analysis was conducted and uses a
t-distribution for posterior predictive checks and checking residuals
for any inadequacies.

<https://iopscience.iop.org/article/10.1088/0026-1394/52/6/878/pdf>

### Bayesian Linear Regression with skew-symmetric error distributions with applications to survival analysis

This article starts with explaining the Bayesian Linear Regression and
how if there is not a strong knowledge of priori, then noninformative
priori can be used instead and looks at different skew symmetric
distributions such as the skew-normal, skew-t, and the skew-logistic.
This article also details the different priors there are (Jeffreys,
Matching, Heuristic, and informative). Once it set up the previous
knowledge needed for Bayesian Linear Regression and skew-symmetric error
distributions, it goes into the example of the survival times of lung
cancer patients. By looking at the previously listed skew symmetric
distributions and comparing it to the scale mixture of normals (SMN),
the use of the skew symmetric distributions captures heterogeneity that
could not be capture by SMN and can explain residual error asymmetry.

<https://repository.kaust.edu.sa/server/api/core/bitstreams/6c7ea8b8-fb7c-48f9-b87a-7261d145a724/content>

## References Week 2

| Klauenberg, Katy, et al. “A tutorial on Bayesian Normal linear
|       regression.” Metrologia, vol. 52, no. 6, 18 Nov. 2015, pp. 878–892,
|       https://doi.org/10.1088/0026-1394/52/6/878.

| Rubio, Francisco J., and Marc G. Genton. “Bayesian linear regression
|       with skew-symmetric error distributions with applications to survival
|       analysis.” Statistics in Medicine, vol. 35, no. 14, 9 Feb. 2016, pp.
|       2441–2454, https://doi.org/10.1002/sim.6897.

## Week 3

### Bayesian Linear Regression analysis of the effect of silica fume on concrete creep predictions and structures’ safety

The goal of this paper is to predict the behavior of certain chemicals on concrete in a construction environment by using bayesian linear regression. This is important to predict before construction begins in the design stage to ensure the safety and longevity of the structure made of concrete. How this problem is solved is by looking at the mean square error and mean deviation of the creep compliance formula which predicts the creep of concrete, the deformation of concrete, which showed that the predictions were overestimating the creep of concrete. Then Bayesian Linear Regression is used to get a more accurate estimate of the creep of concrete by using the likelihood function from the database for this data as the priori and using updated knowledge for the posterior from a more updated database. As a result of using Bayesian Linear Regression, adding a correction coefficient of the creep compliance formula and considering the use of silica fume can more accurately predict the creep of concrete. 

<https://www.sciencedirect.com/science/article/pii/S2452321620300184?via%3Dihub>

### Determining passenger car equivalent (PCEs) for pretimed signalized intersections with severe motorcycle composition using Bayesian linear regression.

The goal of this paper is to use Bayesian Linear Regression to determine the most efficient flow rate of vehicles while also considering the number of vehicles at an intersection. This is important to prevent traffic, reduce energy consumption, reduce air pollution, and more. In this paper, traffic data was collected from certain intersections with several hundreds of cycles of data from morning and night observations being collected for this study. This problem is solved by first looking at the likelihood function for the priori and the posterior from later knowledge. As a result, PCE values (or traffic-flow rate values) were determined for motorcycles, cars, and rickshaws. The PCE values were more accurate overall, but especially for the motorcycles. Some limitations of this study were that only three of the busiest intersections in Indonesia were studied; therefore, this study should be expanded further. Some other limitations include how the signals worked at the different intersections, the design of the intersections, and the movement within the intersections which weren’t considered. 

<https://go-gale-com.ezproxy.lib.uwf.edu/ps/i.do?p=AONE&u=pens49866&id=GALE%7CA674089533&v=2.1&it=r&aty=ip>

## References Week 3

| Sugiarto, Sugiarto, et al. “Determining passenger car equivalent (pces) for
|       pretimed signalized intersections with severe motorcycle composition using
|       Bayesian linear regression.” PLOS ONE, vol. 16, no. 9, 2 Sept. 2021,
|       https://doi.org/10.1371/journal.pone.0256620. 

| Zgheib, Elise, and Wassim Raphael. “Bayesian linear regression analysis of the
|       effect of silica fume on concrete creep predictions and structures’ safety.”
|       Procedia Structural Integrity, vol. 22, 2019, pp. 25–32,
|       https://doi.org/10.1016/j.prostr.2020.01.004. 


## Week 4

### Genomic-Enabled Prediction Based on Molecular Markers and Pedigree Using the Bayesian Linear Regression Package in R

The goal of this paper is to predict genetic values for genomic selection (GS) for plants and animals by using bayesian linear regression, specifically the BLR package in R. This is important for the development of gene selection in plants, animals and humans to prevent the risk of passing on genes that could cause illnesses. This is solved by using the prior distribution to solve the posterior distribution. The BLR package uses cross validation (for comparing models) while using gene data from wheat crops and is used to compare different methods. For example, functions such as rnorm() and runif() pull randomly from the distributions in the article. This use of the BLR package in R resulted in being able to compare different models if wanted (BRR vs BL) and can do so efficiently, regardless of how large the dataset(s) might be. One important takeaway from this article was that different priors will result in different results; however, it’s possible for it to result in the same estimates as well (such as when a gene is dependent on a certain marker). 

<https://acsess.onlinelibrary.wiley.com/doi/pdfdirect/10.3835/plantgenome2010.04.0005>

### Long-term bridge performance assessment using clusteringand Bayesian linear regression for vehicle load and strainmapping model

The goal of this paper is to use Bayesian Linear Regression to determine the safety of a bridge. There are systems in place that assess bridge safety by assessing vehicle weight and speed, with vehicle weight being one of the main sources of bridge failures. Some methods were developed looking at specific weights on vehicles, like axle weights to determine bridge failure, as well as truck loads being on bridges. This is important due to bridges needing to assessed for safety and capacity management and with bayesian linear regression, this can reduce the uncertainty of the model. First, the article adds the vehicle weight to the normal distribution to make the prior distribution, which is the same form as the posterior distribution. Bayesian linear regression is used for the vehicle load and the strain on the bridge from the vehicle. This resulted in a correlation between the weight of a vehicle, along with the strain that the vehicle can put on the bridge. 

<https://onlinelibrary-wiley-com.ezproxy.lib.uwf.edu/doi/epdf/10.1002/stc.3118>

## References Week 4

| Pérez, Paulino, et al. “Genomic‐enabled prediction based on molecular markers and
|       pedigree using the Bayesian linear regression package in R.” The Plant Genome,
|       vol. 3, no. 2, Sept. 2010, https://doi.org/10.3835/plantgenome2010.04.0005. 

| Zhang, Xiaonan, et al. “Long‐term bridge performance assessment using clustering
|       and Bayesian linear regression for vehicle load and strain mapping model.”
|       Structural Control and Health Monitoring, vol. 29, no. 12, 5 Oct. 2022,
|       https://doi.org/10.1002/stc.3118. 